memes/urls.py
from django.urls import path
from . import views

urlpatterns = [
               path('review/<int:pk>', views.AddComments.as_view(), name='add_comments'),
               path('mem/<slug:mem_slug>/', views.MemDetail.as_view(), name='mem'),
               path('category/<slug:cat_slug>/', views.ShowCategory.as_view(), name='category'),
               path('addmem/', views.AddMem.as_view(), name='add_mem'),
               path('update_mem/<slug:mem_slug>/', views.UpdateMem.as_view(), name='update_mem'),
               path('login/', views.LoginUser.as_view(), name="login"),
               path('register/', views.RegisterUser.as_view(), name="register"),
               path('logout/', views.logout_user, name="logout"),
               path('contact/', views.ContactFormView.as_view(), name='contact'),
               path('', (views.MemesView.as_view()), name='home')]

memsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('memes.urls'))
]
urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
        # path('captcha/', include('captcha.urls')),
    ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memes/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Memes(models.Model):
    '''Мемы с тачками'''
    objects = None
    name = models.CharField('Название мема', max_length=30)
    img = models.ImageField('Мем', upload_to='image/%Y')
    date = models.DateField('Дата')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT)
    author = models.CharField('Автор мема', max_length=30)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")

    def get_absolute_url(self):
        return reverse('mem', kwargs={'mem_slug': self.slug})

    class Meta:
        verbose_name = 'Мемы'
        verbose_name_plural = 'Мемы'
        ordering = ['id']


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']


class Comments(models.Model):
    '''Комментарии'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=1000)
    mem = models.ForeignKey(Memes, verbose_name='Мем', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.name}, {self.mem}'

memes/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, FormView, UpdateView
from django.views.generic.base import View

from .form import CommentsForm, AddMemForm, RegisterUserForm, LoginUserForm, ContactForm, UpdateMemesForm
from .models import Memes, Category
from .utils import DataMixin


# Create your views here.

# class MemesView(View):
#     '''Вывод мемов'''
#     def get(self, request):
#         memes = Memes.objects.all()
#         return render(request, 'memsite/memsite.html', {'mem_list': memes, 'title': 'Балдёжные мэмы', 'theme_selected': 'Главная'})

class MemesView(DataMixin, ListView):
    '''Вывод мемов'''
    model = Memes
    template_name = 'memsite/memsite.html'
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Балдёжные мэмы', theme_selected='Главная')
        return dict(list(context.items()) + list(c_def.items()))

# class Show_category(View):
#     '''Отдельная категория'''
#     def get(self, request, cat_slug):
#
#         cat_selected = Category.objects.all().get(slug=cat_slug)
#         cat_id = cat_selected.id
#         memes = Memes.objects.filter(cat_id=cat_id)
#
#         if len(memes) == 0:
#             raise Http404()
#
#         return render(request, 'memsite/cat_selected.html', {'mems': memes, 'cat_selected': cat_selected, 'title': 'a', 'theme_selected': cat_selected})

class ShowCategory(DataMixin, ListView):
    '''Отдельная категория'''
    model = Memes
    template_name = 'memsite/cat_selected.html'
    context_object_name = 'mems'
    allow_empty = False
    paginate_by = 2

    def get_queryset(self):
        return Memes.objects.filter(cat__slug=self.kwargs['cat_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c = Category.objects.get(slug=self.kwargs['cat_slug'])
        c_def = self.get_user_context(title=f'Мемы категории {str(c.name)}', cat_selected=c.pk)
        return dict(list(context.items()) + list(c_def.items()))


class AddComments(View):
    '''добавление комментариев'''
    def post(self, request, pk):
        form = CommentsForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.mem_id = pk
            form.save()
        mem = Memes.objects.all().get(id=pk)
        mem_slug = mem.slug
        return redirect(f'/mem/{mem_slug}/')

# class MemDetail(View):
#     '''Отдельный мем'''
#     def get(self, request, mem_slug):
#         mem = Memes.objects.get(slug=mem_slug)
#         return render(request, 'memsite/mem_detail.html', {'mem': mem, 'title': mem.name, 'theme_selected': mem.cat})

class MemDetail(DataMixin, DetailView):
    '''Отдельный мем'''
    model = Memes
    template_name = 'memsite/mem_detail.html'
    slug_url_kwarg = "mem_slug"
    context_object_name = 'mem'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title=context['mem'].name)
        return dict(list(context.items()) + list(c_def.items()))

# def addmem(request):
#     if request.method == 'POST':
#         form = AddMemForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/')
#     else:
#         form = AddMemForm()
#     return render(request, 'memsite/addmem.html', {'form': form, 'title': 'Добавить мем', 'url_name': 'add_mem', 'theme_selected': 'Добавить мем'})

class AddMem(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddMemForm
    template_name = 'memsite/addmem.html'
    login_url = '/admin/'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Добавить мем', update_mode=False)
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class UpdateMem(LoginRequiredMixin, DataMixin, UpdateView):
    model = Memes
    form_class = UpdateMemesForm
    template_name = 'memsite/addmem.html'
    login_url = '/admin/'
    slug_field = 'slug'
    slug_url_kwarg = 'mem_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Редактировать мем', update_mode=True, meme=self.get_object())
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'memsite/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Регистрация', update_mode=True)
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'memsite/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title='Авторизация')
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')

def logout_user(request):
    logout(request)
    return redirect('login')

class ContactFormView(DataMixin, FormView):

    form_class = ContactForm
    template_name = 'memsite/contact.html'
    success_url = reverse_lazy('home')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Обратная связь")
        return dict(list(context.items()) + list(c_def.items()))

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('home')

memes/templates/memsite/addmem.html
{% extends 'memsite/base.html' %}

{% block content %}
  <h1>{{ title }}</h1>

  {% if update_mode %}
    <form action="{% url 'update_mem' mem_slug=meme.slug %}" method="post" enctype="multipart/form-data">
  {% else %}
    <form action="{% url 'add_mem' %}" method="post" enctype="multipart/form-data">
  {% endif %}
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Сохранить</button>
    </form>
{% endblock %}

memes/templates/memsite/base.html
{% load static %}
{% load mem_tags %}
<html>
<head>
	<title>{{ title }}</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />


</head>
<body>
<div class="shell">
	<div class="border">

		{% show_categories %}


		<div id="main">
			<div id="content" class="left">

		{% block content %}

		{% endblock %}

			</div>
		</div>

		<div class="cl">&nbsp;</div>
	</div>


	</div>
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
{% if page_obj.has_previous %}
<li class="page-num">
	<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
</li>
{% endif %}

        {% for p in paginator.page_range %}
		{% if page_obj.number == p %}
        <li class="page-num page-num-selected">{{ p }}</li>
		{% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
		{% endif %}
        {% endfor %}

{% if page_obj.has_next %}
<li class="page-num">
	<a href="?page={{ page_obj.next_page_number }}">&gt;</a>
</li>
{% endif %}

    </ul>
</nav>
{% endif %}
	</div>
	<div id="footer">
		<p class="copy right">Copyright &copy;  2022 </p>
	</div>
</div>
</body>
</html>

memes/templates/memsite/cat_selected.html
{% extends 'memsite/base.html' %}
{% block content %}
<div class="projects">
					<p>Мемы категории {{ cat_selected.name }}</p>
					{% for mem in mems %}
					<h1><a href="{{ mem.get_absolute_url }}">{{ mem.name }}</a></h1>
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ mem.img.url }}" width="250px" /></a>
							<p>{{ mem.date }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</form>
					</div>
					</div>
					<br>
					<br>
					<br>
					<br>
					{% endfor %}
{% endblock %}

memes/templates/memsite/contact.html
{% extends 'memsite/base.html' %}
{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Отправить</button>
</form>
{% endblock %}

memes/templates/memsite/list_categories.html
{% load mem_tags %}
{% load static %}

		<div id="navigation">
			<ul>
				<li><a href="/">Главная</a></li>
			    <li><a href="/admin">Админ панель</a></li>
				<div>
				<ul class='dropdown'>
					{% get_categories as categories %}
		     		<li id="top"><a>Категории мемов</a>
		     			<span></span>
						<div id="navi">
		        		<ul class="dropdown-box">
						{% for c in categories %}
						{% if c.pk == cat_selected %}
						<li class="selected">{{c.name}}</li>
						{% else %}
						<li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
						{% endif %}
						{% endfor %}
		        		</ul>
						</div>
		     		</li>
				</ul>
					<li><a href="/contact">Обратная связь</a></li>
					{% if auth == 1 %}
						<li><a href="/addmem">Добавить мем</a></li>
					{% endif %}
					{% if auth == 1 %}
						<li class="last"><a href="{% url 'logout' %}"> {{user.username}} Выйти</a></li>
					{% else %}
						<li class="last"><a href="{% url 'register' %}">Регистрация</a> | <a href="{% url 'login' %}">Войти</a></li>
					{% endif %}
				</div>
			</ul>
		</div>

memes/templates/memsite/login.html
{% extends 'memsite/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

<div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Войти</button>
</form>

{% endblock %}

memes/templates/memsite/mem_detail.html
{% load static %}
{% load mem_tags %}
<html>
<head>
	<title>{{ title }}</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />


</head>
<body>
<div class="shell">
	<div class="border">

		{% show_categories %}

		<div id="main">
			<div id="content" class="left">

				<div class="projects">
					<h3>{{ mem.name }}</h3>
                    <p align="center">
                        <img src="{{ mem.img.url }}" width="50%px" />
                    </p>
					<div class="item">
						<div class="text left">
							<p>Автор:  {{ mem.author }}</p>
						</div>
						<div class="cl">&nbsp;</div>
					</div>
				</div>

			</div>
			<div class="form-comment">
				<h3>Оставить комментарий</h3>
				<div>
					<form action="{% url 'add_comments' mem.id %}" method="post">
						{% csrf_token %}
						<div>
							<label>Ваш комментарий</label>
							<textarea name="text_comments"></textarea>
						</div>
						<div>
							<label>Ваше имя *</label>
							<input type="text" name="name">
						</div>
						<div>
							<label>Ваш email *</label>
							<input type="email" name="email">
						</div>
						<div>
							<input type="submit">
						</div>
					</form>
				</div>
			<br>
			<br>
			<div>
				{% for comment in mem.comments_set.all %}
					<div class="view-comment">
						<h4>{{ comment.name }}</h4>
						<p>{{ comment.text_comments }}</p>
					</div>
				{% endfor %}
			</div>
			</div>


			<div class="cl">&nbsp;</div>
		</div>


	</div>

	<div id="footer">
		<p class="copy right">Copyright &copy;  2022 </p>
	</div>
</div>
</body>
</html>

memes/templates/memsite/memsite.html
{% extends 'memsite/base.html' %}
{% block content %}

<div class="projects">
					<h3>Мемы</h3>
					{% for mem in object_list %}
					<h1><a href="{{ mem.get_absolute_url }}">{{ mem.name }}</a></h1>
					<div class="item">
						<div class="image left">
							<a href="#"><img src="{{ mem.img.url }}" width="250px" /></a>
							<h3>{{ mem.date }}</h3>
						</div>
						<div class="cl">&nbsp;</div>
					</form>
					</div>
					</div>
					<br>
					<br>
					<br>
					<br>
					{% endfor %}
{% endblock %}

memes/templates/memsite/register.html
{% extends 'memsite/base.html' %}

{% block content %}
<h1>{{ title }}</h1>

<form method="post">
    {% csrf_token %}
{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Регистрация</button>
</form>

{% endblock %}